version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: bigspawn/devops-for-programmers-project-lvl1:latest
    container_name: service-app
    command: ["npm", "start"]
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - db
  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
  db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
