version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: bigspawn/devops-for-programmers-project-lvl1:latest
    container_name: service-app
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "test"]
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:13.4-alpine
    restart: always
    container_name: service-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
