FROM node:14.16
WORKDIR /app

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm install --build-from-source=bcrypt

COPY app/. .

COPY wait-for-it.sh wait-for-it.sh

EXPOSE 8080

CMD ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]